<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReservationSeeder extends Seeder
{
    // The number of washing machines generated by the seeder.
    private const NUMBER_OF_WASHING_MACHINES = 2;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // first, create the two washing machines
        $washing_machines = [
            ReservableItem::create([
                "name" => "The machine on the left",
                "type" => "washing_machine",
                "default_reservation_duration" => 60,
                "is_default_compulsory" => true,
                "allowed_starting_minutes" => "0"
            ]),
            ReservableItem::create([
                "name" => "The machine on the right",
                "type" => "washing_machine",
                "default_reservation_duration" => 60,
                "is_default_compulsory" => true,
                "allowed_starting_minutes" => "0"
            ]),
        ];
    }
}
