#  DB_CONNECTION=mysql
#  DB_HOST=127.0.0.1
#  DB_PORT=3306 (overriden by 8011 for tests)

version: '3'
services:
    mars_mysql:
        container_name: mars_mysql
        image: 'mysql:8.3'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - './data/mysql:/var/lib/mysql'
    mars_mysql_test:
        container_name: mars_mysql_test
        image: 'mysql:8.3'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '127.0.0.1:8011:3306'
