@can('viewSomeApplication', \App\Models\User::class)
    @switch($status)
        @case(\App\Models\ApplicationForm::STATUS_IN_PROGRESS)
            Folyamatban
            @break
        @case(\App\Models\ApplicationForm::STATUS_SUBMITTED)
            Véglegesítve
            @break
        @case(\App\Models\ApplicationForm::STATUS_BANISHED)
            Elutasítva
            @break
        @case(\App\Models\ApplicationForm::STATUS_CALLED_IN)
            Behívva
            @break
        @case(\App\Models\ApplicationForm::STATUS_ACCEPTED)
            Felvéve
            @break
        @default
            <i>Ismeretlen</i>
    @endswitch
@endcan
@cannot('viewSomeApplication', \App\Models\User::class)
    @switch($status)
        @case(\App\Models\ApplicationForm::STATUS_IN_PROGRESS)
            Folyamatban
            @break
        @default
            Véglegesítve
    @endswitch
@endcannot
