on: [ pull_request ]
name: CI
jobs:
  refresh-ide-helper:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Generate ide-helper comments
        run: php artisan ide-helper:refresh

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config --global --add safe.directory /__w/${{ github.repository }} # Add your repo's directory as safe

      - name: Commit changes
        run: |
          git add .
          git commit -m "Refresh ide-helper automatically" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main

